#!/bin/bash

current_dir=$(pwd)
GPT_PATH=$current_dir/script/gpt.py

if [ ! -f ./venv/bin/activate ]; then
    echo "Creating virtual environment..."
    python3 -m venv venv
    source ./venv/bin/activate
    pip install -r requirements.txt
fi

exec python3 $GPT_PATH "$@"
